# Generated by Django 4.1.5 on 2023-03-22 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CriptoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('symbol', models.CharField(max_length=10, verbose_name='Symbol')),
                ('price', models.FloatField(default=0, verbose_name='Price')),
                ('percent_change_24h', models.FloatField(default=0, verbose_name='Price change for 24 hours')),
                ('volume_24h', models.FloatField(default=0, verbose_name='Selling volume for 24 hours')),
                ('volume_change_24h', models.FloatField(default=0, verbose_name='Selling volume change for 24 hours')),
            ],
        ),
        migrations.CreateModel(
            name='FavouriteCripto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cripto', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fave_cripto', to='app_cripto.criptomodel')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
