# Generated by Django 4.1.5 on 2023-03-22 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cripto', '0002_alter_criptomodel_percent_change_24h_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criptomodel',
            name='percent_change_24h',
            field=models.FloatField(default=0, verbose_name='Price change for 24 hours'),
        ),
        migrations.AlterField(
            model_name='criptomodel',
            name='price',
            field=models.FloatField(default=0, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='criptomodel',
            name='volume_24h',
            field=models.FloatField(default=0, verbose_name='Selling volume for 24 hours'),
        ),
        migrations.AlterField(
            model_name='criptomodel',
            name='volume_change_24h',
            field=models.FloatField(default=0, verbose_name='Selling volume change for 24 hours'),
        ),
    ]
