# Generated by Django 4.1.5 on 2023-03-22 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_cripto', '0003_alter_criptomodel_percent_change_24h_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favouritecripto',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fave_cripto_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
